import '@/styles/globals.css';
import { Footer } from '@/components/footer';
import { Header } from '@/components/header';
import { ThemeProvider } from '@/components/theme-provider';
import { dmMono, robotoSlab } from '@/fonts';
import type { Metadata } from 'next';

type RootLayoutProps = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: {
    default: 'Yuki Takagi',
    template: `%s | Yuki Takagi`,
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en' className={`${dmMono.variable} ${robotoSlab.variable}`}>
      <head />
      <body className='px-6 font-sans'>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <main className='m-auto w-3/4 max-w-max  py-3'> {children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
