import { Inter_Tight } from 'next/font/google';
import './globals.css';
import { Header } from '@/app/header';
import type { Metadata } from 'next';

const inter = Inter_Tight({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='m-auto w-2/3 max-w-full p-10'>
          <Header />
          {children}
        </div>
        <table>
          <thead>
            <tr>
              <th>Year</th>
              <th></th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
      </body>
    </html>
  );
}
