import type { Metadata } from 'next';

const nameVar: string = 'Yuki Takagi';
const descVar: string = 'Generated by create next app';

export const RootMetadata: Metadata = {
  generator: 'Next.js',
  applicationName: 'Next.js',
  referrer: 'origin-when-cross-origin',
  keywords: ['Next.js', 'React', 'JavaScript'],
  authors: [{ name: nameVar, url: 'https://nextjs.org' }],
  creator: nameVar,
  publisher: nameVar,
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  title: {
    default: nameVar,
    template: `%s | ${nameVar}`,
  },
  description: descVar,
  manifest: 'https://nextjs.org/manifest.json',
  twitter: {
    card: 'summary_large_image',
    title: nameVar,
    description: descVar,
    siteId: '1467726470533754880',
    creator: '@nextjs',
    creatorId: '1467726470533754880',
    images: ['https://nextjs.org/og.png'], // Must be an absolute URL
  },
  category: 'technology',
};
